server:
  port: 9216 #设置端口

spring:
  redis:
    database: 3    #1库：运营平台  #2库：商户系统 #3库：支付网关

# knife4j APIDOC文档
knife4j:
  documents:
    - group: 支付网关
      name: 接口文档
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/doc/*

# Jeepay多级缓存配置
jeepay:
  cache:
    multi-level:
      enabled: true
      key-prefix: jeepay
      cache-null-values: true
      # L1缓存(Caffeine)配置 - payment
      l1:
        enabled: true
        maximum-size: 10000
        expire-after-write: 5
        expire-after-access: 15
        initial-capacity: 1000
        record-stats: true
      # L2缓存(Redis)配置
      l2:
        enabled: true
        default-ttl: 1800
      # 统计配置
      stats:
        enabled: true
        interval: 60
