server:
  port: 9218 #设置端口

spring:
  redis:
    database: 2    #1库：运营平台  #2库：商户系统 #3库：支付网关

#系统业务参数
isys:
    jwt-secret: ARNXp4MzjOOQqxtv #生成jwt的秘钥。 要求每个系统有单独的秘钥管理机制。

# Jeepay多级缓存配置
jeepay:
  cache:
    multi-level:
      enabled: true
      key-prefix: jeepay
      cache-null-values: true
      # L1缓存(Caffeine)配置 - merchant
      l1:
        enabled: true
        maximum-size: 3000
        expire-after-write: 10
        expire-after-access: 30
        initial-capacity: 300
        record-stats: true
      # L2缓存(Redis)配置
      l2:
        enabled: true
        default-ttl: 1800
      # 统计配置
      stats:
        enabled: true
        interval: 60

